### ISSUE TITLE
Character Not Displaying

### ISSUE THREAD

**Issue by RedFireMRT84** [AerGlass/wii-stuff#1]
When I ran my own executable (.dol), after the GRRLIB logo, my character doesn't display. The VPS emulation even stops at 60% and 100%.
Video showcase:
https://user-images.githubusercontent.com/126342520/221385859-0fbd2b33-43ee-44df-9050-a2a06882c930.mp4
Also here's my source code:
[platform_v0.1.0_RedFire.zip](https://github.com/AerGlass/wii-stuff/files/10832615/platform_v0.1.0_RedFire.zip)

**Comment by AerGlass** [comment]
fixed (comunication via discord)
